import type { Project } from "./types";

/** Asegura campos del portal y del pipeline nuevos si el JSON es anterior. */
export function ensureProject(p: Partial<Project> & Pick<Project, "id">): Project {
  return {
    id: p.id,
    sourceId: p.sourceId ?? "bocm",
    sourceLabel: p.sourceLabel ?? "Homes",
    territorioId: p.territorioId ?? "comunidad-madrid",
    territorioLabel: p.territorioLabel ?? "Comunidad de Madrid",
    bocmDate: p.bocmDate ?? "",
    artNum: p.artNum ?? "",
    title: p.title ?? "",
    pdfUrl: p.pdfUrl ?? null,
    municipio: p.municipio ?? "",
    tipoInstrumento: p.tipoInstrumento ?? "",
    nombreSector: p.nombreSector ?? "",
    estadoTramitacion: p.estadoTramitacion ?? "",
    fechaAcuerdo: p.fechaAcuerdo ?? null,
    organo: p.organo ?? "",
    promotor: p.promotor ?? null,
    numViviendas: p.numViviendas ?? null,
    supTotalM2: p.supTotalM2 ?? null,
    supEdificableM2: p.supEdificableM2 ?? null,
    tipoVivienda: p.tipoVivienda ?? null,
    resumen: p.resumen ?? "",
    municipioProvincia: p.municipioProvincia ?? "",
    categoriasTematicas: p.categoriasTematicas ?? null,
    economicoResumen: p.economicoResumen ?? null,
    procedimientoExpediente: p.procedimientoExpediente ?? null,
    procedimientoTipo: p.procedimientoTipo ?? null,
    importeTotalEur: p.importeTotalEur ?? null,
    requiereSegundaPasada: Boolean(p.requiereSegundaPasada),
    charsTextoTotal: p.charsTextoTotal ?? null,
    lat: p.lat ?? null,
    lng: p.lng ?? null,
    sectorKey: p.sectorKey ?? null,
    sectorGeoKey: p.sectorGeoKey ?? null,
    coordSource: p.coordSource ?? null,
    esRelevante: p.esRelevante ?? null,
    parseError: p.parseError ?? null,
    sigmaMatchType: p.sigmaMatchType ?? null,
    sigmaMatchScore: p.sigmaMatchScore ?? null,
    sigmaExpediente: p.sigmaExpediente ?? null,
    sigmaDenominacion: p.sigmaDenominacion ?? null,
    sigmaFase: p.sigmaFase ?? null,
    sigmaEnlace: p.sigmaEnlace ?? null,
    sigmaEnIp: Boolean(p.sigmaEnIp),

    sigmaCatalogSyncedAt: p.sigmaCatalogSyncedAt ?? null,
    sigmaFiguraCodigo: p.sigmaFiguraCodigo ?? null,
    sigmaTipoFigura: p.sigmaTipoFigura ?? null,
    sigmaOrganoTramitador: p.sigmaOrganoTramitador ?? null,
    sigmaCatalogSource: p.sigmaCatalogSource ?? null,
    sigmaSigmaLayerKind: p.sigmaSigmaLayerKind ?? null,
    sigmaObjectId: p.sigmaObjectId ?? null,
    sigmaFechaAprobacion: p.sigmaFechaAprobacion ?? null,
    sigmaInfopublicaInicio: p.sigmaInfopublicaInicio ?? null,
    sigmaInfopublicaFin: p.sigmaInfopublicaFin ?? null,
    sigmaHasGeometrySigma: p.sigmaHasGeometrySigma === true,

    sigmaBoletinMismaExpediente: p.sigmaBoletinMismaExpediente ?? undefined,

    sigmaVisorFetchedAt: p.sigmaVisorFetchedAt ?? null,
    sigmaVisorUrl: p.sigmaVisorUrl ?? null,
    sigmaVisorCabecera: p.sigmaVisorCabecera ?? undefined,
    sigmaVisorTramitacion: p.sigmaVisorTramitacion ?? undefined,
    sigmaVisorDocumentacionUrls: p.sigmaVisorDocumentacionUrls ?? undefined,
    sigmaVisorNtiListadoUrl: p.sigmaVisorNtiListadoUrl ?? null,
    sigmaVisorNtiDocumentosTotal: p.sigmaVisorNtiDocumentosTotal ?? null,
    sigmaVisorNtiDocumentosMuestra: p.sigmaVisorNtiDocumentosMuestra ?? undefined,
  };
}
