import { ensureProject } from "./ensure-project";
import type { Project } from "./types";

type ProyectoRow = Record<string, unknown>;

export function projectFromDominioRow(row: ProyectoRow): Project {
  const pubDate = row.bocm_pub_date
    ? String(row.bocm_pub_date).slice(0, 10)
    : "";
  return ensureProject({
    id: String(row.bocm_primary_id ?? row.id ?? ""),
    sourceId: String(row.bocm_source_id ?? "bocm"),
    sourceLabel: "Homes",
    territorioId: "comunidad-madrid",
    territorioLabel: "Comunidad de Madrid",
    bocmDate: pubDate,
    artNum: String(row.bocm_art_num ?? ""),
    title: String(row.bocm_title ?? ""),
    pdfUrl: (row.bocm_pdf_url as string | null) ?? null,
    municipio: String(row.bocm_municipio ?? row.municipio ?? ""),
    tipoInstrumento: String(row.bocm_tipo_instrumento ?? ""),
    nombreSector: String(row.bocm_nombre_sector ?? ""),
    estadoTramitacion: String(row.bocm_estado_tramitacion ?? ""),
    fechaAcuerdo: (row.bocm_fecha_acuerdo as string | null) ?? null,
    organo: String(row.bocm_organo ?? ""),
    promotor: (row.bocm_promotor as string | null) ?? null,
    numViviendas: (row.num_viviendas_max as number | null) ?? null,
    supTotalM2: (row.sup_total_m2 as number | null) ?? null,
    supEdificableM2: (row.sup_edificable_m2 as number | null) ?? null,
    tipoVivienda: (row.tipo_vivienda as string | null) ?? null,
    resumen: String(row.bocm_resumen ?? ""),
    municipioProvincia: String(row.bocm_municipio_provincia ?? ""),
    categoriasTematicas: (row.bocm_categorias_tematicas as string | null) ?? null,
    economicoResumen: (row.bocm_economico_resumen as string | null) ?? null,
    procedimientoExpediente: (row.bocm_procedimiento_expediente as string | null) ?? null,
    procedimientoTipo: (row.bocm_procedimiento_tipo as string | null) ?? null,
    importeTotalEur: (row.importe_total_eur as number | null) ?? null,
    requiereSegundaPasada: Boolean(row.bocm_requiere_segunda_pasada),
    charsTextoTotal: (row.bocm_chars_texto_total as number | null) ?? null,
    lat: (row.lat as number | null) ?? null,
    lng: (row.lng as number | null) ?? null,
    sectorKey: (row.sector_key as string | null) ?? null,
    sectorGeoKey: (row.sector_geo_key as string | null) ?? null,
    coordSource: (row.coord_source as string | null) ?? null,
    esRelevante: (row.bocm_es_relevante as boolean | null) ?? null,
    parseError: (row.bocm_parse_error as string | null) ?? null,
    sigmaMatchType: (row.bocm_sigma_match_type as string | null) ?? null,
    sigmaMatchScore: (row.bocm_sigma_match_score as number | null) ?? null,
    sigmaExpediente: (row.expediente_grupo as string | null) ?? null,
    sigmaDenominacion: (row.denominacion as string | null) ?? null,
    sigmaFase: (row.fase as string | null) ?? null,
    sigmaEnlace: String(row.enlace ?? row.sigma_enlace_snapshot ?? "") || null,
    sigmaEnIp: row.sigma_layer_kind === "informacion_publica",
    sigmaCatalogSyncedAt: (row.sigma_synced_at as string | null) ?? null,
    sigmaFiguraCodigo: (row.figura_codigo as string | null) ?? null,
    sigmaTipoFigura: (row.tipo_figura as string | null) ?? null,
    sigmaOrganoTramitador: (row.organo_tramitador as string | null) ?? null,
    sigmaCatalogSource: (row.catalog_source as string | null) ?? null,
    sigmaSigmaLayerKind: (row.sigma_layer_kind as string | null) ?? null,
    sigmaObjectId: (row.object_id as number | null) ?? null,
    sigmaFechaAprobacion: (row.fecha_aprob as string | null) ?? null,
    sigmaInfopublicaInicio: (row.infopublica_inicio as string | null) ?? null,
    sigmaInfopublicaFin: (row.infopublica_fin as string | null) ?? null,
    sigmaHasGeometrySigma: row.has_geometry === true,
    sigmaVisorFetchedAt: (row.visor_fetched_at as string | null) ?? null,
    sigmaVisorUrl: (row.visor_url as string | null) ?? null,
    sigmaVisorCabecera: (row.visor_cabecera as Project["sigmaVisorCabecera"]) ?? null,
    sigmaVisorTramitacion: (row.tramitacion as Project["sigmaVisorTramitacion"]) ?? undefined,
    sigmaVisorDocumentacionUrls: (row.documentacion_urls as string[]) ?? undefined,
    sigmaVisorNtiListadoUrl: (row.nti_listado_url as string | null) ?? null,
    sigmaVisorNtiDocumentosTotal: (row.nti_documentos_total as number | null) ?? null,
    sigmaVisorNtiDocumentosMuestra:
      (row.nti_documentos_muestra as Project["sigmaVisorNtiDocumentosMuestra"]) ?? undefined,
  });
}
